const products = [
  {
    _id: "641e887d05f9ee1717e1348a",
    sku: "NTB7SDVX44",
    img: "https://lomonoxop.edu.vn/images/ckeditor/images/lomonoxop/cay%20luoi%20ho.png",
    title: "Cây Lưỡi Hổ",
    slug: "cay-luoi-ho",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây cảnh để bàn",
    children: "Cây lưỡi hổ",
    price: 200000,
    discount: 0,
    quantity: 15,
    brand: {},
    category: {
      name: "Cây cảnh để bàn",
      id: "641d424bdbfab7b02ab28b95",
    },
    status: "in-stock",
    reviews: ["6461c46a9154b65448da799f"],
    productType: "plants",
    description:
      "Cây lưỡi hổ có khả năng lọc không khí và rất dễ chăm sóc. Phù hợp trang trí văn phòng, nhà ở.",
    additionalInformation: [
      { key: "Chiều cao", value: "20-30cm" },
      { key: "Ánh sáng", value: "Ánh sáng gián tiếp" },
    ],
    featured: true,
    sellCount: 5,
    tags: ["Cây để bàn", "Lưỡi hổ", "Trang trí nội thất"],
  },
  {
    _id: "641e887d05f9ee1717e1348b",
    sku: "NTB7SDVX45",
    img: "https://example.com/cay-kim-tien.png",
    title: "Cây Kim Tiền",
    slug: "cay-kim-tien",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây cảnh để bàn",
    children: "Cây kim tiền",
    price: 250000,
    discount: 0,
    quantity: 10,
    brand: {},
    category: {
      name: "Cây cảnh để bàn",
      id: "641d424bdbfab7b02ab28b95",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Kim Tiền mang đến tài lộc, dễ chăm sóc, thích hợp để bàn làm việc.",
    additionalInformation: [
      { key: "Chiều cao", value: "30-40cm" },
      { key: "Ánh sáng", value: "Ánh sáng yếu" },
    ],
    featured: false,
    sellCount: 8,
    tags: ["Cây để bàn", "Kim Tiền", "Trang trí nội thất"],
  },
  {
    _id: "641e887d05f9ee1717e1348c",
    sku: "NTB7SDVX46",
    img: "https://example.com/cay-phat-tai.png",
    title: "Cây Phát Tài",
    slug: "cay-phat-tai",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây cảnh để bàn",
    children: "Cây phát tài",
    price: 220000,
    discount: 0,
    quantity: 12,
    brand: {},
    category: {
      name: "Cây cảnh để bàn",
      id: "641d424bdbfab7b02ab28b95",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Phát Tài mang lại may mắn, phù hợp với không gian sống và văn phòng.",
    additionalInformation: [
      { key: "Chiều cao", value: "40-50cm" },
      { key: "Ánh sáng", value: "Ánh sáng trung bình" },
    ],
    featured: false,
    sellCount: 3,
    tags: ["Cây để bàn", "Phát Tài", "Trang trí"],
  },
  {
    _id: "641e887d05f9ee1717e1348d",
    sku: "NTB7SDVX47",
    img: "https://example.com/cay-trau-ba.png",
    title: "Cây Trầu Bà",
    slug: "cay-trau-ba",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây thuỷ sinh",
    children: "Cây trầu bà",
    price: 180000,
    discount: 0,
    quantity: 20,
    brand: {},
    category: {
      name: "Cây thuỷ sinh",
      id: "6419723bd7dc5155c04350d4",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Trầu Bà rất thích hợp trang trí trong bể cá hay thủy sinh, giúp lọc nước và tạo không gian xanh.",
    additionalInformation: [
      { key: "Chiều cao", value: "15-25cm" },
      { key: "Ánh sáng", value: "Ánh sáng tự nhiên" },
    ],
    featured: true,
    sellCount: 7,
    tags: ["Cây thuỷ sinh", "Trầu Bà", "Trang trí"],
  },
  {
    _id: "641e887d05f9ee1717e1348e",
    sku: "NTB7SDVX48",
    img: "https://example.com/reeu-thuy-sinh.png",
    title: "Rêu Thủy Sinh",
    slug: "reu-thuy-sinh",
    unit: "1 mảng",
    imageURLs: [],
    parent: "Cây thuỷ sinh",
    children: "Rêu thuỷ sinh",
    price: 120000,
    discount: 0,
    quantity: 25,
    brand: {},
    category: {
      name: "Cây thuỷ sinh",
      id: "6419723bd7dc5155c04350d4",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Rêu thủy sinh giúp tạo lớp nền xanh và trang trí bể cá một cách sinh động.",
    additionalInformation: [
      { key: "Kích thước", value: "10x10cm" },
      { key: "Ánh sáng", value: "Ánh sáng yếu" },
    ],
    featured: false,
    sellCount: 5,
    tags: ["Cây thuỷ sinh", "Rêu", "Trang trí bể cá"],
  },
  {
    _id: "641e887d05f9ee1717e1348f",
    sku: "NTB7SDVX49",
    img: "https://example.com/chau-nho.png",
    title: "Chậu đất nung nhỏ",
    slug: "chau-dat-nung-nho",
    unit: "1 chậu",
    imageURLs: [],
    parent: "Chậu đất nung",
    children: "Chậu nhỏ",
    price: 50000,
    discount: 0,
    quantity: 50,
    brand: {},
    category: {
      name: "Chậu đất nung",
      id: "6419723bd7dc5155c04350d5",
    },
    status: "in-stock",
    reviews: [],
    productType: "pots",
    description:
      "Chậu đất nung nhỏ phù hợp với cây cảnh mini và trang trí bàn làm việc.",
    additionalInformation: [
      { key: "Đường kính", value: "10cm" },
      { key: "Chất liệu", value: "Đất nung" },
    ],
    featured: false,
    sellCount: 12,
    tags: ["Chậu đất nung", "Chậu nhỏ", "Trang trí cây cảnh"],
  },
  {
    _id: "641e887d05f9ee1717e13490",
    sku: "NTB7SDVX50",
    img: "https://example.com/chau-vuong.png",
    title: "Chậu bonsai vuông",
    slug: "chau-bonsai-vuong",
    unit: "1 chậu",
    imageURLs: [],
    parent: "Chậu bonsai",
    children: "Chậu vuông",
    price: 80000,
    discount: 0,
    quantity: 30,
    brand: {},
    category: {
      name: "Chậu bonsai",
      id: "6419723bd7dc5155c04350d6",
    },
    status: "in-stock",
    reviews: [],
    productType: "pots",
    description:
      "Chậu bonsai vuông là lựa chọn lý tưởng cho việc trồng bonsai, tạo điểm nhấn nghệ thuật.",
    additionalInformation: [
      { key: "Kích thước", value: "15x15cm" },
      { key: "Chất liệu", value: "Gốm sứ" },
    ],
    featured: true,
    sellCount: 9,
    tags: ["Chậu bonsai", "Chậu vuông", "Trang trí bonsai"],
  },
  {
    _id: "641e887d05f9ee1717e13492",
    sku: "NTB7SDVX51",
    img: "https://example.com/cay-lan-y.png",
    title: "Cây Lan Ý",
    slug: "cay-lan-y",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây cảnh để bàn",
    children: "Cây Lan Ý",
    price: 230000,
    discount: 0,
    quantity: 18,
    brand: {},
    category: {
      name: "Cây cảnh để bàn",
      id: "641d424bdbfab7b02ab28b95",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Lan Ý giúp thanh lọc không khí và mang lại sự bình an, thích hợp trang trí phòng làm việc.",
    additionalInformation: [
      { key: "Chiều cao", value: "25-35cm" },
      { key: "Ánh sáng", value: "Ánh sáng gián tiếp" },
    ],
    featured: false,
    sellCount: 6,
    tags: ["Cây để bàn", "Lan Ý", "Trang trí nội thất"],
  },
  {
    _id: "641e887d05f9ee1717e13493",
    sku: "NTB7SDVX52",
    img: "https://example.com/cay-beo.png",
    title: "Cây Bèo",
    slug: "cay-beo",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây thuỷ sinh",
    children: "Cây bèo",
    price: 90000,
    discount: 0,
    quantity: 30,
    brand: {},
    category: {
      name: "Cây thuỷ sinh",
      id: "6419723bd7dc5155c04350d4",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Bèo là cây thủy sinh dễ chăm sóc, có khả năng lọc nước và tạo không gian xanh cho bể cá.",
    additionalInformation: [
      { key: "Kích thước", value: "5-10cm" },
      { key: "Ánh sáng", value: "Ánh sáng yếu" },
    ],
    featured: false,
    sellCount: 15,
    tags: ["Cây thuỷ sinh", "Bèo", "Trang trí bể cá"],
  },
  {
    _id: "641e887d05f9ee1717e13494",
    sku: "NTB7SDVX53",
    img: "https://example.com/chau-trung.png",
    title: "Chậu đất nung trung",
    slug: "chau-dat-nung-trung",
    unit: "1 chậu",
    imageURLs: [],
    parent: "Chậu đất nung",
    children: "Chậu trung",
    price: 70000,
    discount: 0,
    quantity: 40,
    brand: {},
    category: {
      name: "Chậu đất nung",
      id: "6419723bd7dc5155c04350d5",
    },
    status: "in-stock",
    reviews: [],
    productType: "pots",
    description:
      "Chậu đất nung trung phù hợp với cây cảnh trung bình, tạo không gian xanh cho ngôi nhà.",
    additionalInformation: [
      { key: "Đường kính", value: "15cm" },
      { key: "Chất liệu", value: "Đất nung" },
    ],
    featured: false,
    sellCount: 8,
    tags: ["Chậu đất nung", "Chậu trung", "Trang trí cây cảnh"],
  },
  {
    _id: "641e887d05f9ee1717e13495",
    sku: "NTB7SDVX54",
    img: "https://example.com/chau-tron.png",
    title: "Chậu bonsai tròn",
    slug: "chau-bonsai-tron",
    unit: "1 chậu",
    imageURLs: [],
    parent: "Chậu bonsai",
    children: "Chậu tròn",
    price: 85000,
    discount: 0,
    quantity: 35,
    brand: {},
    category: {
      name: "Chậu bonsai",
      id: "6419723bd7dc5155c04350d6",
    },
    status: "in-stock",
    reviews: [],
    productType: "pots",
    description:
      "Chậu bonsai tròn là lựa chọn hoàn hảo cho các loại bonsai nhỏ, giúp trang trí không gian sống.",
    additionalInformation: [
      { key: "Đường kính", value: "14cm" },
      { key: "Chất liệu", value: "Gốm sứ" },
    ],
    featured: true,
    sellCount: 10,
    tags: ["Chậu bonsai", "Chậu tròn", "Trang trí bonsai"],
  },
  {
    _id: "641e887d05f9ee1717e13496",
    sku: "NTB7SDVX55",
    img: "https://example.com/cay-chanh.png",
    title: "Cây Chanh",
    slug: "cay-chanh",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây ăn trái",
    children: "Cây chanh",
    price: 300000,
    discount: 0,
    quantity: 15,
    brand: {},
    category: {
      name: "Cây ăn trái",
      id: "6419723bd7dc5155c04350d7",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Chanh dễ chăm sóc, thích hợp trồng tại nhà, cung cấp trái và giúp làm đẹp không gian.",
    additionalInformation: [
      { key: "Chiều cao", value: "40-50cm" },
      { key: "Ánh sáng", value: "Ánh sáng trực tiếp" },
    ],
    featured: true,
    sellCount: 5,
    tags: ["Cây ăn trái", "Chanh", "Trang trí vườn nhà"],
  },
  {
    _id: "641e887d05f9ee1717e13497",
    sku: "NTB7SDVX56",
    img: "https://example.com/sen-da-xanh.png",
    title: "Sen Đá Xanh",
    slug: "sen-da-xanh",
    unit: "1 cây",
    imageURLs: [],
    parent: "Sen đá, xương rồng",
    children: "Sen đá xanh",
    price: 120000,
    discount: 0,
    quantity: 25,
    brand: {},
    category: {
      name: "Sen đá, xương rồng",
      id: "64200cb921162f8b15beae3e",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Sen Đá Xanh là loài cây nhỏ gọn, dễ chăm sóc, phù hợp với không gian nhỏ và bàn làm việc.",
    additionalInformation: [
      { key: "Chiều cao", value: "5-10cm" },
      { key: "Ánh sáng", value: "Ánh sáng yếu" },
    ],
    featured: false,
    sellCount: 20,
    tags: ["Sen đá", "Trang trí nội thất", "Cây mini"],
  },
  {
    _id: "641e887d05f9ee1717e13498",
    sku: "NTB7SDVX57",
    img: "https://example.com/cay-day-nhen.png",
    title: "Cây Dây Nhện",
    slug: "cay-day-nhen",
    unit: "1 cây",
    imageURLs: [],
    parent: "Cây chậu treo",
    children: "Dây nhện",
    price: 180000,
    discount: 0,
    quantity: 20,
    brand: {},
    category: {
      name: "Cây chậu treo",
      id: "64200cef21162f8b15beae40",
    },
    status: "in-stock",
    reviews: [],
    productType: "plants",
    description:
      "Cây Dây Nhện phù hợp trồng trong chậu treo, giúp không gian thêm tươi mát và sinh động.",
    additionalInformation: [
      { key: "Chiều dài", value: "15-20cm" },
      { key: "Ánh sáng", value: "Ánh sáng gián tiếp" },
    ],
    featured: true,
    sellCount: 9,
    tags: ["Cây treo", "Dây Nhện", "Trang trí nhà cửa"],
  },
];

module.exports = products;
